### ISSUE TITLE
uthev uleste innlegg

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RUSK#12]
- Farvelegg tråd-linjer for tråder med uleste innlegg.
- Skriv om trådlinken til å gå til første uleste innlegg så det ikke bare er det lille ikonet som fører deg dit.
- Inne på tråden kan kanskje bakgrunnen på de nye innleggene farvelegges?

**Comment by havremunken** [comment]
Alle disse tingene er ivaretatt i RFS, så jeg foreslår at vi gjør noe lignende som der. I tillegg så er det keyboard navigation på tråder og poster som automatisk hopper til nyeste uleste osv. Jeg er helt avhengig av denne funksjonaliteten for å leve så den vil jeg gjerne fortsatt ha ja. :)

**Comment by larsjaas** [comment]
Ja, jeg legger bare inn all funksjonalitet vi allerede har så vi får de ned som "issues" som kan sjekkes av, knyttes til extension-versjoner, og huskes for release notes og dokumentasjon. Er klar over at alt dette er selvsagt, og havner i extensionen selv uten issues på dem :)

**Comment by havremunken** [comment]
Den er god, enig i at det er en god idé, tenkte bare å unngå duplication of effort. :)

**Comment by havremunken** [comment]
Nå håper jeg at jeg skal ha det grunnleggende på plass for å implementere denne, så da gjør jeg det.

**Comment by havremunken** [comment]
Lukker denne da den gjør det den skal i utgangspunktet - absolutt forbedringspotensiale, men det får komme i senere issues.
