### ISSUE TITLE
signatur-filter

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RUSK#14]
Må gå an å sjekke av signaturen til enkelt-brukere så man slipper å se den igjen, i alle fall til de får endret innhold.

**Comment by larsjaas** [comment]
Nåh, hvilken forum-tråd var det gollumLAD legend skrev mest i, igjen?

**Comment by larsjaas** [comment]
Prototype på plass. Mangler:
- hash'e signatur-innholdet for å ha verdi å lagre unna og sammenligne med for endringer
- persistere hvilke brukere man filtrerer signatur med en gitt hash-verdi for
- GUI-elementer for å knerte og gjenopplive signaturen til, tilpasset current flter-state
- live oppdatering av GUI om man bytter mellom filtrering og ikke filtrering av en signatur
Masse gjenstår å gjøre med andre ord :( men mulig jeg parkerer denne for en liten stund...

**Comment by havremunken** [comment]
Nice :D

**Comment by larsjaas** [comment]
kun global opsjon for denne milepælen

**Comment by larsjaas** [comment]
Det ble også context-menu item for individuell signatur-dreping.
