### ISSUE TITLE
Skjuling av tråder

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/RUSK#15]
Ser for meg to elementer i dette:

- Klikke på tråd for å skjule den "for alltid" (mulig å fjerne fra lista igjen)
- Regexp for å skjule tråder som matcher (for de som ikke vil se resultattips f.eks.)

**Comment by larsjaas** [comment]
Utfordring (sannsynligvis enkel) på denne er å få skjulte tråder markert som lest, slik at forumforsiden ikke viser at det er uleste innlegg i underforumet. Kanskje vi til og med kan gjøre dette via noe direkte cookie-manipulering?

**Comment by havremunken** [comment]
Jeg kjenner ikke formatet til phpbb i det hele tatt, men "auto-unread for alltid" hadde jo vært toppen av genialitet!

**Comment by larsjaas** [comment]
done
