### ISSUE TITLE
RFC: Struktur på plugins / moduler

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/RUSK#2]
Ser for meg å videreutvikle modul-prinsippet fra Forum Suite med typescript, slik at hver funksjonalitet vi legger til kan avgrenses og testes i noe nært opptil isolasjon.

Det betyr at en modul må ha noen funksjoner (init, deinit, blabla) som vi kaller opp for at den skal få gjort greia si. En modul må på et vis erklære hvilke sider den skal brukes for (url-matching), vi bør kanskje vurdere et tall-parameter som angir rekkefølge den vil kjøre i (eller holder med at de kan angi "early", "normal" og "late" f.eks.?), og så bør vi kanskje vurdere å tilby noen "hooks" som en plugin kan hekte seg på for å reagere på page lifecycle events - om dette har noen særlig verdi.

Forum Suite er ganske enkel her - det er stort sett en modul pr. sidetype. Spørsmålet er om trolls-be-gone eller annen funksjonalitet har spesielle behov her. Holder det å bare bli kalt opp på ett-eller-annet-tidspunkt etter at siden er lastet inn? Bør vi lage litt avanserte lifecycle-ting, eller er det totalt overkill?

Satser i utgangspunktet tungt på YAGNI og at vi kan gjøre dette ganske enkelt. Men det er greit å ha en plan. 

Å kunne teste moduler vha. qunit e.l. hadde vært veldig fint, men det er kanskje urealistisk å få til noe særlig av dette.

**Comment by larsjaas** [comment]
Føler dette kan starte temmelig minimalt, og utvikles/innvikles etterhvert som det kommer behov.

**Comment by havremunken** [comment]
Har levert første naive implementasjon. Hovedelementet et typescript-interfacet ExtensionModule. Dette er utgangspunktet for all funksjonalitet i Chrome ext. På denne måten får vi isolert alle tilleggsfunksjoner i sin egen "silo", samt sikret at alt oppfører seg på en måte som gjør systemet noenlunde forutsigbart.

Det er en del som står igjen. Ikke-komplett liste:

- Modulsystemet leser config fra sync storage og mater inn i hver ExtMod.
- Modulsystemet sorterer ExtMods korrekt etter runBefore og runAfter.
- Kjører kun ExtMods som matcher korrekt med urlsToRunOn.
- Når/hvordan skal vi hente config tilbake fra ExtMods til sync storage? Etter settings GUI oppdatert er selvfølgelig, men hva om en bruker legger til et troll i trolls-be-gone-modulen? Bør sync'es umiddelbart just in case kanskje?

**Comment by havremunken** [comment]
Ser for meg en runde til med breaking changes når jeg legger inn nytt config-opplegg. En init-metode hvor extmod får servert config, og kanskje noe mer relatert til dette. At bruker endrer innstillinger i settings UI vil håndteres der, men extmod må ha en måte å varsle at config endret seg i løpet av dens kjøretid sånn at vi kan lagre unna - eksempelvis når en bruker legger til et nytt troll ved å klikke på noe i et forum view.

**Comment by havremunken** [comment]
init() og preprocess() er på plass som "lifecycle events". Tenker å innføre en base class for extmods så vi slipper å implementere ting som ikke er i bruk.

**Comment by havremunken** [comment]
Jeg erklærer at dette er ok foreløpig. Det VIL garantert komme endringer, men vi har gjort det issuet handlet om.
