### ISSUE TITLE
rendering optimisation

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RUSK#27]
En IMG-tag som inneholder "width" og "height" blir det vel allokert riktig plass til på websiden før den rendres, slik at når bildet er innlastet så skulle det ikke føre til side-justeringer og re-layout. Mulig at om alle avatarer og embeddede bilder fikk injisert width/height-parametre, så ville html-rendering kunne gå litt raskere.

Dagens hardware har vel ikke dette som noen bottleneck akkurat, men om man ser visse bildedelings-tjenester er trege og fører til ulemper for htmlrendering, så kunne man kanskje sett på å cache data for dette, kanskje også sentralisert/delt.

**Comment by havremunken** [comment]
Det gir meg en tanke - litt på siden av det du tenker på her, men likevel litt relatert.

Klarer vi på noen måte å måle hvor lang tid det tar å laste inn et gitt bilde? Isåfall kunne vi jo forsøke å måle dette for hver avatar, og tilbudt brukeren å droppe avatarer som går over en eller annen terskelverdi. Dette spiller jo igjen inn på den andre greia med å fjerne slemme avatarer.

**Comment by larsjaas** [comment]
kontinuerlig fokusområde. lukkes som issue.
