### ISSUE TITLE
tweet-embedding

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RUSK#32]
Twitter-link til tweet-embedding.

Relatert: #1

**Comment by larsjaas** [comment]
Mulig tweet-embedding ikke lar seg gjøre i HTML (for posting), og at vi vil trenge å ha en service som tar en twitter-URL og genererer en png som uploades til imgur e.l. og legges inn som bilde-link. I browse-mode er det kanskje enklere å injisere twitter-html basert på en twitter-url.

**Comment by havremunken** [comment]
Jeg mener å ha sett injiserte tweets på websider som er forholdsvis dynamiske (oppdatert med antall likes og retweets f.eks.), så jeg antar at denne siden av saken lar seg løse.

For posting er jeg usikker, så kanskje man bare må støtte seg til "media embedding" ala #1 for at det skal bli riktig.

**Comment by larsjaas** [comment]
Litt kult om det var png-embdding som fallback, som ble overstyrt/erstattet når rbkwb-ext kjente igjen twitteren den hadde postet og heller la inn dertil egnet html. Best of both worlds...

**Comment by larsjaas** [comment]
"Close and comment"... Trenger en GitHub-ext for å holde meg unna den...

**Comment by larsjaas** [comment]
avslutter denne da RUSK-brukere nå får embeddede tweets - tror ikke vi gidder tilrettelegge for posting av bilder av tweets for ikke-RUSK-brukere.
