### ISSUE TITLE
tracke brukernavn-endringer

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RUSK#36]
Ligger i Trolls-Be-Gone.
Dict på {userid: username}. Når en post har kjent brukerid, ukjent brukernavn så får brukernavnet teksten "aka gammelt" under, pluss en checkbox man klikker når man er fornøyd med varslingen. Når den klikkes blir dict'en oppdatert med nytt brukernavn.

**Comment by havremunken** [comment]
Bare ut av interesse - hvordan blir dette hvis noen bytter brukernavn, og så bytter igjen før man klikker bort varslingen? Da antar jeg at det navnet "imellom" forsvinner?

**Comment by larsjaas** [comment]
Navnet imellom, som brukeren sannsynligvis ikke har sett en gang, får du da ikke vite om. Funker helt perfekt.

**Comment by larsjaas** [comment]
Har kommet frem til at denne ikke trenger hent inn data fra Trolls-Be-Gone, siden brukeren enten allerede har sett melding om en bruker som har byttet nickname, ellers så vil han sannsynligvis rekke å se eksisterende brukernavn før neste bruker bytter til nytt navn uansett. Og om en nick-endring klarer å smette inn akkurat imellom bruk av Trolls-Be-Gone og RBKweb Survival Kit (om vi ender opp med å kalle ext det) så er man uansett ikke dårligere stilt enn en vanlig rbkweb-bruker...

**Comment by larsjaas** [comment]
Merarbeid kommer når persistent config er klart.
