### ISSUE TITLE
Auto-import av info fra "gamle" scripts

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/RUSK#38]
Når en bruker begynner å bruke ext, bør utvidelsen - så langt det lar seg gjøre - forsøke å hente innstillinger fra de gamle scriptene våre, slik at trolls fortsatt be trolls osv.

Man trenger kanskje så et flagg som sier "har gjort det" så man ikke fortsetter å overskrive troll-lista med gamle innstillinger etter første gang.

**Comment by larsjaas** [comment]
Data som er gjemt bort i GreaseMonkey sin setValue()/getValue() kan muligens være litt vanskelig å få aksess til?

**Comment by havremunken** [comment]
Kan være ja. Er en idé da å oppdatere våre nåværende scripts til å lagre en kopi i localStorage eller noe sånt, sånn at vi får tak i det når ext kommer ut?

**Comment by larsjaas** [comment]
Lurer på om dette er mer arbeid enn det er verdt. Hvor mange troll har folk filtrert bort på det meste? 10? Og tror vi ikke de brukerene husker hvilke brukere (og tråder) det var (og i alle fall minnes på dt umiddelbart når de ser kilden til frustrasjon igjen), og kjappere repeterer filter/kill-aksjonen for de 10 enn vi kan forsvare rotet med ekstra-koden for å lese over gamle innstillinger - som vil være nyttig én gang og deretter bare ligge der til besvær?
