### ISSUE TITLE
bookmarking

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RUSK#4]
Attaboy etterspurte bookmark'ing av topics i forbindelse med Trollescriptet. Følte det ble litt out-of-scope for det scriptet, samt det må dra inn større mengder data som ikke ligger på siden allerede når man skal bla opp bokmerkene man har gjort. Tror det kanskje er en bedr "fit" for en chrome-extension.
Tenker det burde være mulig å lagre unna nok info om bokmerkene til å presentere de ordentlig uten rbkweb.no backend-involvering. Det bør gå an å bokmerke både tråder og enkelt-innlegg.

**Comment by havremunken** [comment]
Absolutt, det skal være forholdsvis trivielt vil jeg tro. Litt simpelt UI for å dra opp det man har bokmerket, og ev. filtrering av det, og noen enkle tastetrykk for å velge/gå til. Liker tanken.

**Comment by larsjaas** [comment]
8K google sync-limit blir fort en issue her om man ikke er smart med lagret datastruktur. Ting må parametriseres og splittes opp - man får ikke mange fulle URLer med subject og author inn i den data-mengden i alle fall.

**Comment by larsjaas** [comment]
Satte max-limit til 25 bokmerker per nå for å prøve å holde folk under 8K settings-bruk. Kan sannsynligvis ha mange flere, men 25 er en fin grense å forholde seg til. Gidder ikke legge til bokmerking av tråder - det er jo bare å sette et bokmerke i tråden i såfall som "workaround".
