### ISSUE TITLE
konfigurere annen highlight-farge for søk

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RUSK#62]
Til meg blir tekst som utheves fordi man har highlight=... i URLen helt hvit, og på hvit bakgrunn er det ukult. Foreslår derfor at vi setter en annen default-farge i RBKweb-ext, og at fargen i tillegg er konfigurerbar.

**Comment by havremunken** [comment]
Dette har irritert meg mange ganger, men sjelden nok til at jeg aldri har gjort noe med det. Gode saker!

**Comment by larsjaas** [comment]
Forfremmer denne like greit til milestone 1. Burde vel være en triviell modul (uten at jeg har sjekket med DOMen)...

**Comment by larsjaas** [comment]
Lukker, så får jobb videre gå undr config-settings-tasken.
