### ISSUE TITLE
Navngi Chrome ext

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/RUSK#63]
Dette har blitt nevnt på gitter og f.eks. i #36, men tenkte vi like gjerne kunne kjøre en issue så vi får det offisielt (pluss masse issues er et tegn på høy aktivitet, right? Så folk tenker at vi har stått på noe sinnsykt).

Beste forslag så langt er `RBKweb Survival Kit`.

Jeg liker det og tenker at det blir det om du ikke kommer opp med noe enda bedre. :)

For kort (i kode eller for å skrive noe kjapt) synes jeg at `RwSK` funker som forkortelse. Hvis enighet, greit at vi "etablerer" denne nå så den får satt seg, før noen utenforstående kommer og døper den noe teit som plutselig blir "standard" på RBKweb osv. :)

**Comment by larsjaas** [comment]
Kanskje vi kan få inn en "a" istedenfor "w" i forkortelsen på ett eller annet vis, så lenge det ikke blir _for_ "forced"?

**Comment by larsjaas** [comment]
Undertask for denne blir å oppdatere README.md, og evt om det er en klasse, html/css-fil eller to som bør få samme navn.

**Comment by havremunken** [comment]
Hehe, jeg liker jo RaSK men da må det bli **R**osenborg **Ba**ll**K**lub web **S**urvival **K**it da.. får ikke rekkefølgen helt til å gå opp.. ;)

**Comment by havremunken** [comment]
En annen greie.. skal vi rename repo nå relativt tidlig i prosessen mens det fortsatt ikke er mye som linker hit? Sikkert mindre trøbbel enn om vi lar være, og så bestemmer oss for å gjøre det allikevel på et senere tidspunkt...

**Comment by larsjaas** [comment]
Tenkte mer sånn "RBKweb Advanced Survival Kit" e.l., men har ikke sansen for Advanced der. Så RwSK får kanskje være greit nok selv om RASK/RISK/RUSK/RØSK vil være missed opportunity.

**Comment by havremunken** [comment]
Ja, ser den. Vi får gi oss selv litt tid til å prøve å komme opp med noe bra nok, ellers lander vi vel fort der. :)

**Comment by havremunken** [comment]
RBKweb User Survival Kit ville gi oss RUSK ev.

**Comment by larsjaas** [comment]
RUSK - RBKweb Ultimate Survival Kit
Det finnes jo en del bøker a'la ... Ultimate Survival Guide, så føler den både kan forsvares seriøst og ironisk...

**Comment by havremunken** [comment]
Hehe, ultimate er kanskje bedre enn user også ja. Det sier jo noe om forventet status på denne extensionen også. ;)

**Comment by larsjaas** [comment]
Begynner å bli få spor igen etter gammelt navn.
