### ISSUE TITLE
docs/-katalog med github pages

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RUSK#71]
Usikker på om det er noe behov - må vel uansett ha en chrome extension store intro-side osv. Github pages blir kanskje en ekstra side som brukes lite og som må holdes i sync?

**Comment by havremunken** [comment]
Ja, vi må sjekke hva vi trenger for at extension stores blir happy. Noe må vi vel ha, så får vi se hvor mye innsats vi legger i det. :)

**Comment by larsjaas** [comment]
Vi driter i egen "github pages" for denne (blir info andre steder).
