### ISSUE TITLE
beskjed i GUI når det finnes en nyere versjon av RUSK som kan lastes ned

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RUSK#79]
...om vi ikke får oppdateringer til å gå ennå mer automatisk da?

**Comment by havremunken** [comment]
Jeg har ikke sett på hvordan mekanismen funker - jeg har aldri bevisst oppdatert f.eks. TamperMonkey, så lurer på om det er et opplegg for det. Men det må vi jo finne ut av. :)

**Comment by larsjaas** [comment]
Det ser ut som om extension-oppdatering vanligvis går helautomatisk for extensionene jeg har installert. Installasjonen kan åpne en side om at den er oppdatert.

**Comment by larsjaas** [comment]
lukker denne.
