### ISSUE TITLE
Config GUI vha. simpel Ember-app

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/RUSK#83]
Vi trenger en GUI for å la brukere gjøre innstillinger.

Plan her og nå:

- Lage en enkel Ember-app som får et config-objekt og dynamisk mekker en GUI
- Få denne til å bygge til en subfolder av dist/-mappa.
- Mekanismer i RUSK som viser denne GUIen. Som en popup? Overlay? De lærde strides.
- Endringer må sendes tilbake til background e.l. for storage.
- ExtMods må få servert oppdatert config gjennom init.
- Tvinge frem en page reload etter config-endring?

**Comment by larsjaas** [comment]
Ember er ikke no krav for min del - jeg liker trivielle ting. :)

**Comment by havremunken** [comment]
Enig i det altså. Tenker bare at siden vi dynamisk må generere config-UI til å tilpasse seg settings som finnes i modulene, så må det være dynamisk. Og da er det Ember jeg kan best for å få dette opp og gå. :)

**Comment by havremunken** [comment]
Denne er jo faktisk fikset for lenge siden. Så sikkert greit å lukke den nå.
