### ISSUE TITLE
Default tråd-liste-link bør gå til nye poster

### ISSUE THREAD

**Issue by larsjaas** [RosenborgSupporterSoftware/RUSK#85]
Når man trykker rett på tittelen til en tråd i et forum eller tilsvarende view, så bør man ikke hoppe til side 1, men til nye poster siden sist man var inne på rbkweb. Dette er funksjonalitet jeg har blitt avhengig av...

**Comment by havremunken** [comment]
Hvis man trykker enter eller L med ColorizeThreads aktiv, velger den etter følgende logikk:

1. Hvis tråden har flere undersider, gå til siste.
2. Gå til førstesiden.

Dette fordi dette er forholdsvis enkelt, men også fordi man kun kan stole på "nye siden sist" hvis man stadig logger inn og ut av RBKweb. Jeg forblir stort sett innlogget, og da er ikke den linken spesielt til å stole på.

For å få dette helt riktig burde vi kanskje basere oss på tracking av siste sette post pr. tråd, som da må implementeres? Isåfall ville jeg jo mer enn gjerne bruke dette istedenfor nåværende mekanisme i ColorizeThreads også.

**Comment by larsjaas** [comment]
Å ta ovr trackingen av hva som er lest, på bedre måte enn rbkweb-cookien tar vi i en egen issue. Det jeg mente over implementerte jeg i går kveld, så denne issuen er done :)
